// <auto-generated />
using Blockbusters.Entities;
using Blockbusters.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Blockbusters.Migrations
{
    [DbContext(typeof(BlockbustersContext))]
    partial class BlockbustersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blockbusters.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Blockbusters.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("RentedAt");

                    b.Property<int>("RentedByCustomerId");

                    b.Property<DateTime?>("ReturnedAt");

                    b.Property<DateTime>("ShouldBeReturnedAt");

                    b.Property<int>("VideoId");

                    b.HasKey("Id");

                    b.HasIndex("RentedByCustomerId");

                    b.HasIndex("VideoId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Blockbusters.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Added");

                    b.Property<string>("ImageUrl");

                    b.Property<int>("LengthInMinutes");

                    b.Property<decimal>("Price");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Blockbusters.Models.Rental", b =>
                {
                    b.HasOne("Blockbusters.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("RentedByCustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Blockbusters.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
